class StudentModel {
  String image;
  String fullName;
  String admissionNumber;
  String gender;
  String address;
  String joiningStandard;
  DateTime dob;
  DateTime joiningDate;
  String medium;
  String firstLanguage;
  String nationality;
  String state;
  String religion;
  String caste;
  String community;
  String motherTongue;
  String previousSchool;
  String previousStandard;
  String fatherName;
  String motherName;
  String fatherOccupation;
  String motherOccupation;
  String fatherQualification;
  String motherQualification;
  String monthlyIncome;
  String mobileNumber;
  String guardianName;
  String guardianAddress;
  String guardianMobileNumber;
  String transport;
  String route;
  String busStop;
  String emisCode;
  String birthCertificate;
  String transferCertificate;
  String aadhaarCard;
  String markSheet;

  StudentModel(
      {required this.image,
      required this.fullName,
      required this.admissionNumber,
      required this.gender,
      required this.address,
      required this.joiningStandard,
      required this.dob,
      required this.joiningDate,
      required this.caste,
      required this.community,
      required this.firstLanguage,
      required this.medium,
      required this.motherTongue,
      required this.nationality,
      required this.previousSchool,
      required this.previousStandard,
      required this.religion,
      required this.state,
      required this.fatherName,
      required this.emisCode,
      required this.busStop,
      required this.route,
      required this.transport,
      required this.guardianAddress,
      required this.guardianMobileNumber,
      required this.guardianName,
      required this.mobileNumber,
      required this.monthlyIncome,
      required this.motherQualification,
      required this.fatherQualification,
      required this.motherOccupation,
      required this.fatherOccupation,
      required this.motherName,
      required this.markSheet,
      required this.aadhaarCard,
      required this.transferCertificate,
      required this.birthCertificate});

  Map<String, dynamic> toJson() {
    return {
      "image": image,
      "full_name": fullName,
      "admission_number": admissionNumber,
      "gender": gender,
      "address": address,
      "joining_standard": joiningStandard,
      "dob": dob,
      "joining_date": joiningDate,
      "medium": medium,
      "first_language": firstLanguage,
      "nationality": nationality,
      "state": state,
      "religion": religion,
      "caste": caste,
      "community": community,
      "mother_tongue": motherTongue,
      "previous_school": previousSchool,
      "previous_standard": previousStandard,
      "father_name": fatherName,
      "mother_name": motherName,
      "father_occupation": fatherOccupation,
      "mother_occupation": motherOccupation,
      "father_qualification": fatherQualification,
      "mother_qualification": motherQualification,
      "monthly_income": monthlyIncome,
      "mobile_number": mobileNumber,
      "guardian_name": guardianName,
      "guardian_mobile_number": guardianMobileNumber,
      "guardian_address": guardianAddress,
      "transport": transport,
      "route": route,
      "bus_stop": busStop,
      "EMIS_code": emisCode,
      "birth_certificate": birthCertificate,
      "transfer_certificate": transferCertificate,
      "aadhaar_card": aadhaarCard,
      "mark_sheet": markSheet,
    };
  }
}
